name: df-parallel-colab
  
channels:
  - rapidsai
  - conda-forge
  - nvidia
  - anaconda

dependencies:
  - python=3.11
  - jupyterlab=4.2.2
#  - dask=2023.3.2
  - dask
  - cudf
  - dask-cudf
#  - cudatoolkit=11.8
